[package]
name = "couchbase"
version = "0.4.0" # remember to update html_root_url
authors = ["Michael Nitschinger <michael.nitschinger@couchbase.com>"]
license = "Apache-2.0"
keywords = ["couchbase", "database", "futures", "libcouchbase", "async"]
categories = ["database", "asynchronous", "caching"]
description = "The Couchbase Rust SDK"
repository = "https://github.com/couchbaselabs/couchbase-rs"
homepage = "https://github.com/couchbaselabs/couchbase-rs"
documentation = "https://docs.rs/couchbase"

[dependencies]
couchbase-sys = { version = "0.4.0", path = "../couchbase-sys" }

url = "1.7"

# futures-preview = "0.3.0-alpha.3"
tokio = "0.1.8"
tokio-channel = "0.1.0"

parking_lot = "0.5"
log = "0.4"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[features]
default = ["build-lcb"]
build-lcb = ["couchbase-sys/build-lcb"]
